#!/usr/bin/env python

import sys
import os

percent = float(sys.argv[1])
width   = int(sys.argv[2]) - 2

if width < 0:
    print('tiny ass progress bar not supported bro')
    os.exit(1)


nchars = round(width * percent)

print('[', end='')
for i in range(nchars):
    print('█', end='')

for i in range(width - nchars):
    print('▁', end='')

print(']')

